// frontend/src/App.jsx
import { useEffect, useState } from "react";

function App() {
  const [message, setMessage] = useState("Loading...");

  useEffect(() => {
    fetch("http://localhost:8000/")
    .then((res) => res.json())
    .then((data) => setMessage(data.message))
    .catch((err) => setMessage("Error: " + err.message));
  }, []);

  return (
    <div style={{ textAlign: "center", marginTop: "50px" }}>
    <h1>FastAPI + React</h1>
    <p>Backend says: {message}</p>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'

const message = ref('Loading...')

onMounted(() => {
  fetch('http://localhost:8000/')
    .then(res => {
      if (!res.ok) throw new Error('Network response was not ok')
      return res.json()
    })
    .then(data => {
      message.value = data.message
    })
    .catch(err => {
      message.value = 'Error: ' + err.message
    })
})
</script>

<template>
  <div style="text-align: center; margin-top: 50px;">
    <h1>FastAPI + Vue</h1>
    <p>Backend says: {{ message }}</p>
  </div>
</template>
